### ISSUE TITLE
English translations

### ISSUE THREAD

**Issue by loboris** [kendryte/kendryte-doc-freertos-programming-guide#1]
When can we expect the english translations?
There is an **en** directory, but with no file in English.

**Comment by vowstar** [comment]
English translation is in progress

https://github.com/kendryte/kendryte-doc-freertos-programming-guide/issues/2

**Comment by loboris** [comment]
Thank you.

**Comment by vowstar** [comment]
Translation completed

**Comment by loboris** [comment]
Great!
Can we expect it in pdf format?

**Comment by vowstar** [comment]
Of course, it is currently under internal review.
